# Generated by Django 3.0.5 on 2020-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(default=397693, editable=False, unique=True)),
                ('user', models.CharField(max_length=50)),
                ('stocks_held', models.CharField(default=None, max_length=2000)),
                ('stock_detail', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('B', 'buy'), ('S', 'sell'), ('T', 'trade'), ('H', 'hold')], default='H', max_length=1)),
                ('up', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_variance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_variance_USD', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time_frame', models.CharField(choices=[('D', '1-day'), ('M', '1-month'), ('Y', '1-year'), ('5', '5-years')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=24986, editable=False, unique=True)),
                ('ticker_symbol', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('up', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
                ('variance_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('variance_USD', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shareholders', models.CharField(default='null', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('followers', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
